### ISSUE TITLE
Expose aiscript capabilities as aiscript-api crate

### ISSUE THREAD

**Issue by Folyd** [aiscriptdev/aiscript#29]
```rs
use aiscript_api::AIScript;

fn main() {
    AIScript::run().unwrap();
}
```

```toml
[package]
name = "hello"
version = "0.1.0"

[dependencies]
aiscript-api = { version = "0.1.0" }
```

```
$ cat web.ai
get /hello {
    return "Hello World!";
}
$ cargo run
Listening on http://localhost:8080
```

```
$ curl http://localhost:8080/hello
Hello World!
```
